#!/bin/bash

# Function to stop and remove a Docker container by name
stop_and_remove_container() {
    if docker ps -a --format '{{.Names}}' | grep -q "^$1$"; then
        echo "Stopping and removing existing container: $1..."
        docker stop $1
        docker rm $1
    else
        echo "No existing container named $1 to remove."
    fi
}

# Stop and remove the 'ollama' and 'open-webui' containers
stop_and_remove_container "ollama"
stop_and_remove_container "open-webui"

# Check if port 3030 is in use and try to free it up
PORT_USER=$(sudo lsof -ti :3030)
if [ ! -z "$PORT_USER" ]; then
    cal
    echo "Port 3030 is in use by process $PORT_USER. Attempting to free it..."
    sudo kill -9 $PORT_USER
else
    echo "Port 3030 is available."
fi

# Run the Docker containers
echo "Starting 'ollama' container..."
docker run -d -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama:latest

echo "Starting 'open-webui' container..."
docker run -d -p 3000:8080 --add-host=host.docker.internal:host-gateway -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:main

echo "Containers are up and running. Waiting for initialization..."
sleep 5 # Adjust sleep as necessary

# Attempt to open localhost:3030 in Firefox
if which firefox > /dev/null; then
    echo "Opening localhost:3030 in Firefox..."
    firefox http://localhost:3000/auth &
else
    echo "Firefox not found. Attempting to open with default browser..."
    xdg-open http://localhost:3030 &
fi
# sudo mv ./llama.sh /usr/local/bin/llama
# sudo chmod +x /usr/local/bin/llama    
